// Generated by Selenium IDE
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.AfterEach;
import com.codeborne.selenide.Configuration;
import com.codeborne.selenide.WebDriverRunner;

import static com.codeborne.selenide.Condition.*;
import static com.codeborne.selenide.Selenide.*;

import org.openqa.selenium.Dimension;

import java.util.*;
public class DemiqaFillFormTest {
  private Map<String, Object> vars;
  @BeforeEach
  public void setUp() {
    Configuration.browser = "chrome";
    vars = new HashMap<>();
  }
  @AfterEach
  public void tearDown() {
  }
  @Test
  public void demiqaFillForm() {
    open("https://demoqa.com/automation-practice-form");
    WebDriverRunner.getWebDriver().manage().window().setSize(new Dimension(1249, 930));
    $("#firstName").click();
    $("#firstName").val("Gtnz");
    $("#lastName").click();
    $("#lastName").val("Petrov");
    $("#userEmail").click();
    $("#userEmail").val("petrov@petrov.com");
    $(".custom-radio:nth-child(1) > .custom-control-label").click();
    $("#userNumber").click();
    $("#userNumber").val("1234567890");
    $("#dateOfBirthInput").click();
    $(".react-datepicker__month-select").click();
    $(".react-datepicker__month-select").selectOption("September");
    $(".react-datepicker__month-select > option:nth-child(9)").click();
    $(".react-datepicker__year-select").click();
    $(".react-datepicker__year-select").selectOption("2007");
    $("option:nth-child(108)").click();
    $(".react-datepicker__day--012:nth-child(4)").click();
    $(".subjects-auto-complete__control").click();
    $("#react-select-2-option-0").click();
    $(".custom-checkbox:nth-child(1) > .custom-control-label").click();
    $(".custom-checkbox:nth-child(1) > .custom-control-label").doubleClick();
    $("#uploadPicture").click();
    $("#uploadPicture").val("C:\\fakepath\\9a0de816-e35f-4ec8-a46f-c8e24e8caedb.jpeg");
    $("#currentAddress").click();
    $("#currentAddress").val("kurshavel");
    $(".css-1pahdxg-control .css-1wa3eu0-placeholder").click();
    $("#react-select-3-option-0").click();
    $(".css-1wa3eu0-placeholder").click();
    $("#react-select-4-option-0").click();
    $("#submit").click();
    $("tr:nth-child(9) > td:nth-child(2)").click();
    $("tr:nth-child(9) > td:nth-child(2)").shouldHave(text("kurshavel"));
    $("#closeLargeModal").click();
  }
}
